[package]
name = "notifs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "0.2.2"
cxx = { version = "1.0.71", features = ["c++20"] }

[build-dependencies]
cc = "1.0.73"
